### ISSUE TITLE
 Rename the helm chart release_name variable to name

### ISSUE THREAD

**Issue by megian** [projectsyn/component-ingress-nginx#26]
## Context
In #25 Kapitan has changed the helm chart name from `release_name` to `name`. Consider a renaming with the next major release.

## Alternatives
Just keep the naming as is.

**Comment by simu** [comment]
From our perspective (Tarazed), there's no need to rename the component parameter. We believe it's good to have parameters which clearly communicate what they're configuring, and with a parameter `name`, I have no idea what's getting configured. Therefore we prefer to keep the component parameter as `release_name`, even if Kapitan's Helm support has changed the parameter.
