### ISSUE TITLE
Monitoring annotation on namespace missing

### ISSUE THREAD

**Issue by laserb** [projectsyn/component-ingress-nginx#4]
This creates a `ServiceMonitor` but the annotation `SYNMonitoring=main` is not set on the namespace and therefore will not get picked up by prometheus.

## Actual Behavior

Annotation not set.

## Expected Behavior

Annotation `SYNMonitoring=main` set.

**Comment by megian** [comment]
The annotation `SYNMonitoring=main` is no longer in use. Closing this issue.
